name: Check Branch Name

on:
  push:
    branches-ignore:
      - "main"
      - "develop"

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name format
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          PATTERN="^(feature|feat|release|hotfix|bugfix|test|docs|chore)\/[a-z0-9-]+$"

          if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
            echo "❌ ERROR: La rama '$BRANCH_NAME' no sigue el estándar de nombres."
            echo "Formatos válidos: feat/mi-rama, hotfix/v1.0.1, chore/update-deps, etc."
            exit 1
          else
            echo "✅ Nombre de rama válido."
          fi
